version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      - dependency-name: "@types/*"
      - dependency-name: "typescript"
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
      - dependency-name: "biome*"
