packages:
  - apps/*
  - internals/*
  - packages/*

overrides:
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  estree-util-value-to-estree@<3.3.3: '>=3.3.3'
  vite@>=6.2.0 <6.2.6: '>=6.2.6'
  vite@>=6.2.0 <=6.2.6: '>=6.2.7'
  vite@>=6.2.0 <6.2.5: '>=6.2.5'
  undici@<5.29.0: '>=5.29.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  next@>=15.3.0 <15.3.3: '>=15.3.3'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  tmp@<=0.2.3: '>=0.2.4'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
