import merge from 'lodash.merge';
import type { Metadata } from 'next';
import { keys } from './keys';

type MetadataGenerator = Omit<Metadata, 'description' | 'title'> & {
  /** Page title. A plain string, or the root template object (`default`/`template`). */
  title: Metadata['title'];
  description: string;
  /**
   * Open Graph image control:
   * - omit → hardcode the default site card (`/opengraph-image`);
   * - a URL → use that page-specific image;
   * - `null` → emit no image in metadata, deferring to the route's own
   *   file-based `opengraph-image` card (used by article routes).
   */
  image?: string | null;
  /**
   * Path (relative to the site root, e.g. `/bio`) used to derive the canonical
   * link and `og:url`. `metadataBase` resolves it to an absolute URL.
   */
  pathname?: string;
};

const applicationName = 'Gabriel Fonseca';
const author: Metadata['authors'] = {
  name: 'Gabriel Fonseca',
  url: 'https://gabfon.com/',
};
const publisher = 'Gabriel Fonseca';
const xHandle = '@gabfon_';
/** Default social card, resolved against `metadataBase` (generated by `opengraph-image`). */
const defaultOgImage = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Gabriel Fonseca — Software Developer',
};
const defaultKeywords = [
  'Gabriel Fonseca',
  'software developer',
  'founder',
  'computer engineering',
  'Lisbon',
  'Portugal',
  'web development',
  'TypeScript',
  'Next.js',
  'portfolio',
  'blog',
];
/** Absolute base for resolving OG/canonical URLs. */
const siteUrl = keys().NEXT_PUBLIC_WEB_URL;

/**
 * Reduce a `title` field (string or template object) to a plain string, used
 * for the fields (`og:title`, apple web app) that require a literal value.
 * @param title - The metadata title field.
 * @returns The resolved title string, or undefined when none can be derived.
 */
const resolveTitleText = (title: Metadata['title']): string | undefined => {
  if (typeof title === 'string') {
    return title;
  }
  if (title && typeof title === 'object') {
    if ('absolute' in title && title.absolute) {
      return title.absolute;
    }
    if ('default' in title && title.default) {
      return title.default;
    }
  }
  return;
};

/**
 * Build a fully-populated Next.js `Metadata` object from a small set of
 * per-page inputs, applying shared defaults (base URL, robots, Open Graph,
 * Twitter card, canonical URL) so every route stays consistent.
 * @param options - The per-page title, description, and optional image/pathname plus any Metadata overrides.
 * @returns A merged `Metadata` object.
 */
export const createMetadata = ({
  title,
  description,
  image,
  pathname,
  ...properties
}: MetadataGenerator): Metadata => {
  const titleText = resolveTitleText(title);

  const defaultMetadata: Metadata = {
    metadataBase: new URL(siteUrl),
    title,
    description,
    applicationName,
    authors: [author],
    creator: author.name,
    publisher,
    keywords: defaultKeywords,
    formatDetection: {
      telephone: false,
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-image-preview': 'large',
        'max-snippet': -1,
        'max-video-preview': -1,
      },
    },
    ...(pathname ? { alternates: { canonical: pathname } } : {}),
    appleWebApp: {
      capable: true,
      statusBarStyle: 'default',
      title: titleText,
    },
    openGraph: {
      title: titleText,
      description,
      type: 'website',
      siteName: applicationName,
      locale: 'en_US',
      ...(pathname ? { url: pathname } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: titleText,
      description,
      creator: xHandle,
      site: xHandle,
    },
  };

  const metadata: Metadata = merge({}, defaultMetadata, properties);

  // Resolve the social card: `null` defers to the route's file-based card;
  // a string uses that image; otherwise hardcode the default site card.
  const resolvedImage =
    image === null ? undefined : (image ?? defaultOgImage.url);

  if (resolvedImage && metadata.openGraph && metadata.twitter) {
    metadata.openGraph.images = [
      {
        url: resolvedImage,
        width: defaultOgImage.width,
        height: defaultOgImage.height,
        alt: titleText ?? defaultOgImage.alt,
      },
    ];
    metadata.twitter.images = [resolvedImage];
  }

  return metadata;
};
